const dropData = [
    { item_name: "Poeira de Oriharucon", monsters: ["Argos", "Argos Errante", "Troul Ghoul", "Caveira", "Urso Zumbi", "Arq. Caveira", "Chefe Ghoul", "Ciclope", "Tauron", "Manticora", "Verme", "Adamant Tauron", "Lugfer", "Cav. Lugfer", "Aranha Rubra", "Aranha Dourada", "Batorero"], zones: ["Sub Mundo", "Dugeon", "Azran", "Deserto", "Kefra"] },
    { item_name: "Poeira de Lactolerium", monsters: ["Argos", "Argos Errante", "Troll Ghoul", "Morlock", "Tauron Pesado", "Manticora", "Verme", "Adamant Tauron", "Lugfer", "Cav. lugfer", "Horizon Cropper", "Xenon Cropper", "Funer Seamer", "Funer Scyther", "Batorero", "Lich Batama", "Lich Crunt"], zones: ["Submundo", "Deserto", "Kefra", "Karden"] },
    { item_name: "Pedra do Sábio", monsters: ["CH Troll Zumbi", "Morlock", "Funner Seamer", "Funner Scyther", "Funer Momenter", "Funer M", "Simio Bleg"], zones: ["Submundo", "Kefra", "Vale Escondido"] },
    { item_name: "Alma Beriel", monsters: ["Rainha Gelo", "Beriel Supremo"], zones: ["Karden"] },
    { item_name: "Coração Beriel", monsters: ["Rainha Gelo", "Beriel Supremo"], zones: ["Karden"] },
    { item_name: "Pedaço do Círculo Divino", monsters: ["Troll Caçador", "Troll", "Meio Orc", "Dragão Menor", "Cavaleiro Orc", "Orc Arqueiro", "Lagarto", "Chefe Krill", "Lobo", "Rei Gremlin", "Caçador Troll", "Gremlin Anct", "Troll Negado"], zones: ["Campo Armia", "Cubo N", "Cubo M"] },
    { item_name: "Pedaço do Círculo Divino Completo", monsters: ["Caçador Chefe", "Caçador Troll", "Guardião", "Espectro", "Trans Master", "Mago Master", "Shama Master", "Hunter Master"], zones: ["Azran", "Cubo M", "Erion", "Lan A", "Lan N"] },
    { item_name: "Símbolo de Vitória", monsters: ["Admiral"], zones: ["Quest Dois Castelos"] },
    { item_name: "Pedra da Luz", monsters: ["Lobo Polar", "Grande Lobo", "Urso Polar", "Troll de Karden", "Ent Anciao"], zones: ["Karden"] },
    { item_name: "Coral", monsters: ["CH Troll Ghoul", "Morlock", "Lobo Polar", "Guerreiro Amon"], zones: ["Sub Mundo", "Noatun", "Karden", "Deserto"] },
    { item_name: "Anhk da Justiça", monsters: ["KalintzAmald", "TauronAmald", "Tauron Assassino", "Trans Master", "Mago Master"], zones: ["Deserto", "Lan M", "Lan A"] },
    { item_name: "Anhk da Eternidade", monsters: ["LoboAmald", "Lugefer Amald", "Lugefer", "Shama Master", "Hunter Master"], zones: ["Deserto", "Lan M", "Lan A"] },
    { item_name: "Ressurreição", monsters: ["LiggleSwarm", "Ent Ancião", "WriggleSwarm", "Simio Ancião", "Verme Agmo", "Valquiria Tina", "KalintzAmald", "LoboAmald", "Valquiria Amald", "Cavaleiro Amald", "Trans Master", "Valquiria", "Rei Carbuncle", "Kalintz Mago", "Guer Kalintz"], zones: ["Cubo A", "Deserto", "Karden", "Lan A", "Lan M", "Pistas de Runas"] },
    { item_name: "Anhk da Glória", monsters: ["Valquiria Amald", "Lugefer Amald", "Lugefer", "Adamant Tauron", "Mestre Hunt", "Hunter Master"], zones: ["Deserto", "Lan M", "Lan A"] },
    { item_name: "Amago de Sleipnir", monsters: ["Funer M"], zones: ["Vale Escondido"] },
    { item_name: "Amago de Svadilfari", monsters: ["Funer M"], zones: ["Vale Escondido"] },
    { item_name: "Diamante", monsters: ["CH Troll Ghoul", "Lobo Polar", "Guerreiro Amon"], zones: ["Sub Mundo", "Noatun", "Karden", "Deserto"] },
    { item_name: "Garnet", monsters: ["Simio Ancião", "Urso Polar", "Grande Lobo", "Guerreiro Amon"], zones: ["Karden"] },
    { item_name: "Esmeralda", monsters: ["Urso Polar", "Grande Lobo"], zones: ["Karden"] },
    { item_name: "Gema da Siren", monsters: ["Lugefer"], zones: ["Deserto de Kefra"] },
    { item_name: "Alma da Fênix", monsters: ["Lich Batama", "Lich Crunt"], zones: ["Kefra"] },
    { item_name: "Alma do Unicórnio", monsters: ["Cav. Lugifer"], zones: ["Kefra", "Vale Escondido"] },
    { item_name: "Selo Mágico", monsters: ["MageKalintz"], zones: ["Pista de Runas +3"] },
    { item_name: "Balmung", monsters: ["Homem Kalintz"], zones: ["Karden"] },
    { item_name: "Skytalos", monsters: ["Homem Kalintz"], zones: ["Karden"] },
    { item_name: "Thrasytes", monsters: ["Homem Kalintz"], zones: ["Karden"] },
    { item_name: "Basileus", monsters: ["Homem Kalintz"], zones: ["Karden"] },
    { item_name: "Caliburn", monsters: ["Homem Kalintz"], zones: ["Karden"] },
    { item_name: "Hophlon", monsters: ["Homem Kalintz"], zones: ["Karden"] },
    { item_name: "Eirenus", monsters: ["Mulher Kalintz"], zones: ["Karden"] },
    { item_name: "Hermai", monsters: ["Mulher Kalintz"], zones: ["Karden"] },
    { item_name: "Khyrius", monsters: ["Mulher Kalintz"], zones: ["Karden"] },
    { item_name: "Neorion", monsters: ["Mulher Kalintz"], zones: ["Karden"] },
    { item_name: "Gleipnir", monsters: ["Mulher Kalintz"], zones: ["Karden"] },
    { item_name: "Bota Flamejante", monsters: ["Troll de Karden"], zones: ["Karden", "Lan M"] },
    { item_name: "Manoplas Flamejante", monsters: ["Lobo Polar"], zones: ["Karden", "Lan M"] },
    { item_name: "Armadura Flamejante", monsters: ["Grande Lobo"], zones: ["Karden", "Lan M"] },
    { item_name: "Calca Flamejante", monsters: ["Soldado Amon"], zones: ["Karden", "Lan M"] },
    { item_name: "Bota Rake", monsters: ["Troll de Karden"], zones: ["Karden", "Lan M"] },
    { item_name: "Manoplas Rake", monsters: ["Lobo Polar"], zones: ["Karden", "Lan M"] },
    { item_name: "Armadura Rake", monsters: ["Grande Lobo"], zones: ["Karden", "Lan M"] },
    { item_name: "Melpômene", monsters: ["Zakum Inf", "Templario Inf", "Guerreiro Elfo"], zones: ["Pista de Runas"] },
    { item_name: "Urânia", monsters: ["Sulrang", "Ranger Inf", "Lich Demo"], zones: ["Pista de Runas"] },
    { item_name: "Poeira Mágica", monsters: ["Beriel Lendario"], zones: ["Quest Moeda Espiritual"] },
    { item_name: "Ovo de Dente de Sabre", monsters: ["Servo Elfo"], zones: ["Quest Inicio da Infelicidade"] },
    { item_name: "Amago de Dente de Sabre", monsters: ["Servo Elfo", "Aranha Venenosa"], zones: ["Quest Inicio da Infelicidade", "Vale Escondido"] },
    { item_name: "Ovo de Cavalo Sem Sela N", monsters: ["Medusa", "Espectro Negro", "Aranha R"], zones: ["Lan A", "Vale Escondido"] },
    { item_name: "Ovo de Cavalo Sem Sela B", monsters: ["Simio Bleg", "Medusa"], zones: ["Dungeon Kefra", "Vale Escondido", "Lan A"] },
    { item_name: "Dríade", monsters: ["Shaman Inf", "Chefe Amon Inf", "Batorero Inf"], zones: ["Pista de Runas"] },
    { item_name: "Potâmides", monsters: ["Mago Inf", "Zakum Inf", "Lugefer Inf,"], zones: ["Pista de Runas"] },
    { item_name: "Calca Rake", monsters: ["Soldado Amon"], zones: ["Karden", "Lan M"] },
    { item_name: "Machado de Osso", monsters: ["Guer Caveira"], zones: ["Dungeon"] },
    { item_name: "Manoplas Destruição", monsters: ["Lobo Polar"], zones: ["Karden", "Lan M"] },
    { item_name: "Armadura Destruição", monsters: ["Grande Lobo"], zones: ["Karden", "Lan M"] },
    { item_name: "Calca Destruição", monsters: ["Soldado Amon"], zones: ["Karden", "Lan M"] },
    { item_name: "Bota guardiã", monsters: ["Troll de Karden"], zones: ["Karden", "Lan M"] },
    { item_name: "Manoplas guardia", monsters: ["Lobo Polar"], zones: ["Karden", "Lan M"] },
    { item_name: "Túnica guardia", monsters: ["Grande Lobo"], zones: ["Karden", "Lan M"] },
    { item_name: "Calca guardia", monsters: ["Soldado Amon"], zones: ["Karden", "Lan M"] },
    { item_name: "Elmo Elemental", monsters: ["HorizonAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Armadura Elemental", monsters: ["HorizonAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Calca Elemental", monsters: ["HorizonAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Luva Elemental", monsters: ["HorizonAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Bota Elemental", monsters: ["HorizonAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Elmo Mytril", monsters: ["AranhaAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Armadura Mytril", monsters: ["AranhaAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Calca Mytril", monsters: ["AranhaAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Luva Mytril", monsters: ["AranhaAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Pedra Tectita", monsters: ["Horizon C", "WriggleSwarm"], zones: ["Dungeon Kefra", "Cubo A"] },
    { item_name: "Pedra Beril", monsters: ["Arq Caveira"], zones: ["Dungeon"] },
    { item_name: "Pedra Spinner", monsters: ["Troll Caos", "Zakum"], zones: ["Duelo M", "Duelo A"] },
    { item_name: "Pedra Adamantita", monsters: ["Adamant Tauron", "Lugefer", "Verme Agmo"], zones: ["Deserto"] },
    { item_name: "Bota Mytril", monsters: ["AranhaAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Elmo Teia", monsters: ["GargulaAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Armadura Teia", monsters: ["GargulaAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Calça Teia", monsters: ["GargulaAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Luva Teia", monsters: ["GargulaAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Bota Teia", monsters: ["GargulaAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Elmo Embutido", monsters: ["MorlockAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Armadura Embutido", monsters: ["MorlockAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Calca Embutido", monsters: ["MorlockAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Luva Embutido", monsters: ["MorlockAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Bota Embutido", monsters: ["MorlockAmald"], zones: ["Lanhouse (N)"] },
    { item_name: "Espada Vorpal", monsters: ["Ent", "Caçador Troll", "Esqueleto", "HorizonAmald", "GargulaAmald", "Verme", "Adamant Tauron"], zones: ["Cubo M", "Cubo A", "Lanhouse (N)", "Deserto"] },
    { item_name: "Lâmina Espiritual", monsters: ["Troll Insano", "Cavaleiro Orc", "Argos"], zones: ["Cubo N", "Cubo M", "SubMundo"] },
    { item_name: "Longinius", monsters: ["Chefe Krill", "Elfo Negro"], zones: ["Cubo N", "Cubo M"] },
    { item_name: "Gungnir", monsters: ["Meio Orc", "Lord Trooper", "Orc L Trooper", "Ciclope Cruel", "Taron Assassino", "Valquiria Tina", "Valquiria Amald", "Rei Gárgula", "Funer M"], zones: ["Cubo N", "Campo Arzan", "Deserto", "Karden", "Lan A", "SubMundo", "Vale Escondido"] },
    { item_name: "Gram", monsters: ["Esqueleto", "Taron Assassino"], zones: ["Cubo N", "Deserto"] },
    { item_name: "Martelo Mythril", monsters: ["Rei Gremlin", "Grim Lock", "Hidra", "Hidra Dourada", "Hezling"], zones: ["Cubo N", "Cubo M", "Dungeon"] },
    { item_name: "Faca do Assassino", monsters: ["Lobo", "Grim Lock"], zones: ["Cubo N", "Cubo M"] },
    { item_name: "Cruz Sagrada", monsters: ["Troll Insano", "Símio", "HorizonAmald", "GargulaAmald", "Verme", "Adamant Tauron", "Lugefer", "Shama Amald", "Ritualista", "Demon Amald", "Espectro", "Lugefer Amald", "Batorero Amald", "Lich Amald", "Trans Master", "Shaman Master", "Demon Gorgon", "Cav.Elfo Negro"], zones: ["Cubo B", "Cubo A", "Lanhouse (N)", "Deserto", "Karden", "Lan A", "Lan N", "SubMundo"] },
    { item_name: "Martelo Assassino", monsters: ["HorizonAmald", "Adamant Tauron"], zones: ["Lanhouse (N)", "Deserto"] },
    { item_name: "Arco Divino", monsters: ["HorizonAmald", "Adamant Tauron"], zones: ["Lanhouse (N)", "Deserto"] },
    { item_name: "Fúria Divina", monsters: ["AranhaAmald", "Manticora"], zones: ["Lanhouse (N)", "Deserto"] },
    { item_name: "Erva de Cura", monsters: [""], zones: ["Cubo da Maldade"] },
    { item_name: "Escama de Bahamut", monsters: ["Lord Tropper", "Lord Cabuncle", "Cav. Lugefer", "Lord Frey"], zones: ["Cubo da Maldade", "Arthas"] },
    { item_name: "Lança Relâmpago", monsters: ["Carbunkle", "Taron Assassino", "Hidra Dourada", "CH Troll Zumbi"], zones: ["Cubo da Maldade N", "Deserto", "Dungeon", "SubMundo"] },
    { item_name: "Faca Astaroth", monsters: ["Zakum Warlok", "Elfo Negro", "Lagarto", "Hezling"], zones: ["Castelo Zakum", "Cubo N", "Cubo M", "Dungeon 1º Andar", "Dungeon 3º Andar"] },
    { item_name: "Cajado Âmbar", monsters: ["GargulaAmald", "Adamant Tauron", "Manticora"], zones: ["Lanhouse (N)", "Deserto"] },
    { item_name: "Garra Draconiana", monsters: ["GargulaAmald", "Adamant Tauron", "Verme"], zones: ["Lanhouse (N)", "Deserto"] },
    { item_name: "Mjolnir", monsters: ["MorlockAmald", "Adamant Tauron"], zones: ["Lanhouse (N)", "Deserto"] },
    { item_name: "Solaris", monsters: ["MorlockAmald", "Adamant Tauron"], zones: ["Lanhouse (N)", "Deserto"] },
    { item_name: "Lança do Triunfo", monsters: ["Adamant Tauron", "Orc Caos", "Troll Insano", "MorlockAmald", "Manticora", "Cav. Lugefer", "Lugefer"], zones: ["Cubo M", "Cubo A", "Lanhouse (N)", "Deserto"] },
    { item_name: "Lança Invisível", monsters: ["Elfo Negro"], zones: ["Cubo M"] },
    { item_name: "Pedra Espiritual", monsters: ["Batorero"], zones: ["Kefra"] },
    { item_name: "Escudo do Guardião", monsters: ["Valquiria Tina", "Guerreiro Amon", "Capitao Amon"], zones: ["Karden"] },
    { item_name: "Pergaminho Selado", monsters: ["Grande Lobo", "Troll de Karden", "Urso Polar", "Ent Anciao"], zones: ["Karden"] },
    { item_name: "Amago de Andaluz N", monsters: ["Aranha Rubra", "Aranha Dourada", "GrubSawrm", "LiggleSawrm"], zones: ["Kefra"] },
    { item_name: "Amago de Andaluz B", monsters: ["Aranha Rubra", "Aranha Dourada", "GrubSawrm", "LiggleSawrm"], zones: ["Kefra"] },
    { item_name: "Ovo de Grifo", monsters: ["Sombra Negra", "Medusa"], zones: ["Pesadelo M", "Lan A"] },
    { item_name: "Foice Platinada", monsters: ["Verid", "Berserker Ref", "Valquiria Tina"], zones: ["Karden"] },
    { item_name: "Selo do Guerreiro", monsters: ["Sombra Negra", "Beriel Supremo"], zones: ["Karden"] },
    { item_name: "Ovo de Pantera Negra", monsters: ["Simio Bleg"], zones: ["Vale Escondido"] },
    { item_name: "Algiz", monsters: ["Eden Supremo"], zones: ["Karden"] },
    { item_name: "Naldhiz", monsters: ["Eden Supremo"], zones: ["Karden"] },
    { item_name: "Jera", monsters: ["Eden Supremo"], zones: ["Karden"] },
    { item_name: "Othila", monsters: ["Eden Supremo"], zones: ["Karden"] },
    { item_name: "Amago de Pantera Negra", monsters: ["Simio Bleg"], zones: ["Vale Escondido"] },
    { item_name: "Amago de Unicórnio", monsters: ["Lich Crunt"], zones: ["Dungeon Kefra"] },
    { item_name: "Amago de Pégasus", monsters: ["Guarda Beriel", "Berserker Ref", "Valquiria Rosen", "Lich Infernal", "Demonio Alado", "Berserker Amald", "Arch Lich", "Verid Infernal", "Lich Batama"], zones: ["Karden", "Dungeon Kefra", "Lan A", "Portão Infernal", "Vale Escondido"] },
    { item_name: "Ovo de Unisus", monsters: ["Ritualista", "Valquiria Tina", "Feiticeiro"], zones: ["Karden"] },
    { item_name: "Ovo de Unicórnio", monsters: ["Templario Amald", "Mago Amald", "Shama Amald", "Ranger Amald", "Tita Berserker", "Valquiria Tina", "Ritualista", "Feiticeiro", "Batedor"], zones: ["Karden"] },
    { item_name: "Brinco de Athena", monsters: ["Orc Medico", "Rei Gremlin", "KalintzAmald", "Trans Master"], zones: ["Azran", "Cubo N", "Lan A", "Lan M"] },
    { item_name: "Brinco de Zeus", monsters: ["Ent Anciao", "Demon Lord", "Cacador Troll", "Chefe Krill"], zones: ["Cubo A", "Cubo M", "Cubo N"] },
    { item_name: "Brinco de Titã", monsters: ["Demon Lord", "Lobo"], zones: ["Cubo A", "Cubo N"] },
    { item_name: "Brinco de Hercules", monsters: ["Gargula Servo"], zones: ["Cubo A"] },
    { item_name: "Brinco de Hecate", monsters: ["Gargula Servo", "Troll Negado", "Lord Cabuncle", "Lagarto", "Lobo Amald", "Shama Master", "Hunter Master"], zones: ["Cubo A", "Cubo M", "Cubo N", "Lan A", "Lan M"] },
    { item_name: "Amago de Unisus", monsters: ["Ritualista", "Valquiria Tina"], zones: ["Karden"] },
    { item_name: "Ovo de HipoGrifo", monsters: ["Sombra Negra", "Medusa", "Rei Carbuncle"], zones: ["Pesadelo A", "Lan A", "Pista +6"] },
    { item_name: "Ovo de Grifo Sangrento", monsters: ["Sombra Negra", "Arch Lich", "Balrog", "Medusa", "Kefra"], zones: ["Pista +5", "Zona Infernal", "Lan A", "Dungeon Kefra"] },
    { item_name: "Amago de Grifo Sangrento", monsters: ["Simio Bleg", "Verid Infernal", "Demonio Alado"], zones: ["Vale Escondido", "Zona Infernal", "Lan A"] },
    { item_name: "Amago de HipoGrifo", monsters: ["Sombra Negra", "Simio Bleg", "Carbuncle Ouro", "Zakum Inf", "Demonio Alado"], zones: ["Pesadelo A", "Vale Escondido", "Pista +6", "Lan A"] },
    { item_name: "Amago de Grifo", monsters: ["Sombra Negra", "Simio Bleg", "Lich Demo", "Batorero Inf", "Demonio Alado"], zones: ["Pesadelo M", "Vale Escondido", "Pista +5", "Lan A"] },
    { item_name: "Amago de Dragão Vermelho", monsters: ["Lich Crunt"], zones: ["Vale Escondido"] },
    { item_name: "Amago de Tigre de Fogo", monsters: ["Lich Batama"], zones: ["Vale Escondido"] },
    { item_name: "Ovo de Dragão Vermelho", monsters: ["Lich Crunt"], zones: ["Vale Escondido"] },
    { item_name: "Ovo de Tigre de Fogo", monsters: ["Lich Batama"], zones: ["Vale Escondido"] },
    { item_name: "Ovo de Andaluz N", monsters: ["Aranha Rubra", "Aranha Dourada", "GrubSawrm", "LiggleSawrm"], zones: ["Kefra"] },
    { item_name: "Ovo de Andaluz B", monsters: ["Aranha Rubra", "Aranha Dourada", "GrubSawrm", "LiggleSawrm"], zones: ["Kefra"] },
    { item_name: "Barra de 50KK", monsters: ["Horizon Cropper", "Xeno Cropper"], zones: ["Kefra"] },
    { item_name: "Emblema da Proteção", monsters: ["Rainha Final", "Rei Carbuncle", "Eden Supremo"], zones: ["Karden", "Pista de Runas +6"] },
    { item_name: "Entrada Portão Infernal", monsters: ["Arch Lich"], zones: ["Zona Infernal"] },
    { item_name: "Unha do Kefra", monsters: ["Lich Batama", "Lich Crunt"], zones: ["Dungeon Kefra"] },
    { item_name: "Cabelo Beriel Amald", monsters: ["Beriel Amald"], zones: ["Castelo de Gelo"] },
    { item_name: "Coração Beriel Amald", monsters: ["Beriel Amald", "Rainha Gelo"], zones: ["Castelo de Gelo"] },
    { item_name: "Folha da Mandrágora", monsters: ["Manticora"], zones: ["Deserto de Kefra"] },
    { item_name: "Pedra Lunar", monsters: ["Rainha Gelo"], zones: ["Karden"] },
    { item_name: "Jóia da Escuridão", monsters: ["Rei Carbunkle", "Rainha Final"], zones: ["Pista +6", "Karden"] },
    { item_name: "Defesa contra Sagrado", monsters: ["Lugefer", "Adamant Tauron"], zones: ["Deserto"] },
    { item_name: "Defesa contra Fogo", monsters: ["Lugefer", "Adamant Tauron"], zones: ["Deserto"] },
    { item_name: "Refinação Abençoada", monsters: ["Lugefer", "Rei Carbuncle"], zones: ["Carta de Duelo A", "Pista de Runas +6"] },
    { item_name: "Defesa contra Gelo", monsters: ["Lugefer", "Adamant Tauron"], zones: ["Deserto"] },
    { item_name: "Defesa contra Relâmpago", monsters: ["Lugefer", "Adamant Tauron"], zones: ["Deserto"] },
    { item_name: "Resto de Lactolerium", monsters: ["Meio Orc", "Orc Cavaleiro", "Troll", "Cacador Troll", "Troll Insano", "Troll Mago", "Argos", "Argos Errante", "Horizon Cropper", "Xeno Cropper", "Funer Seamer", "Funer Scyther", "Lich Batama", "Lich Crunt"], zones: ["Erion", "Submundo", "Kefra"] },
    { item_name: "Resto de Oriharucon", monsters: ["Rei Gremlin", "Lizard", "Meio Orc", "Orc Cavaleiro", "Troll", "Cacador Troll", "Troll Insano", "Troll Mago", "Argos", "Argos Errante", "Horizon Cropper", "Xeno Cropper", "Funer Seamer", "Funer Scyther", "Lich Batama", "Lich Crunt"], zones: ["Erion", "Submundo", "Kefra"] },
    { item_name: "Moeda de 200K", monsters: ["Meio Orc", "Troll", "Troll Insano", "AranhaAmald", "HorizonAmald", "MorlockAmald", "GargulaAmald"], zones: ["Erion", "Lanhouse (N)"] },
    { item_name: "Ovo de Equipe B", monsters: ["Troll Chaos"], zones: ["Erion"] },
    { item_name: "Ovo de Equipe N", monsters: ["Troll Chaos"], zones: ["Erion"] },
    { item_name: "Amago de Equipe B", monsters: ["Troll Chaos"], zones: ["Erion"] },
    { item_name: "Amago de Fenrir das Sombras", monsters: ["Simio"], zones: ["Vale Escondido"] },
    { item_name: "Amago de Equipe N", monsters: ["Troll Chaos"], zones: ["Erion"] },
    { item_name: "Ovo de Fenrir", monsters: ["Ladrão Tauron"], zones: ["Deserto"] },
    { item_name: "Amago de Fenrir", monsters: ["Ladrão Tauron"], zones: ["Deserto"] },
    { item_name: "Força Espectral", monsters: ["Sombra Negra", "Amazona Negra", "Lich Batama", "Lich Crunt", "Lich Amald"], zones: ["Lan A", "Dungeon Kefra", "Vale Escondido", "Castelo de Gelo"] },
    { item_name: "Força Eterna", monsters: ["Guarda Beriel", "Valquiria Tina", "Valquiria Rosen", "Titã Berserker"], zones: ["Castelo de Gelo"] },
    { item_name: "Concentração", monsters: ["Sombra Negra", "Amazona Negra", "Lich Batama", "Lich Crunt", "Lich Amald"], zones: ["Castelo de Gelo", "Lan A", "Dungeon Kefra", "Vale Escondido"] },
    { item_name: "Machado Gaoth Selado", monsters: ["Templario Inf", "Mago Inf", "Shaman Inf", "Ranger Inf"], zones: ["Pista +4"] },
    { item_name: "Eithna Seladoo", monsters: ["Templario Inf", "Mago Inf", "Shaman Inf", "Ranger Inf"], zones: ["Pista +4"] },
    { item_name: "Lupercus Selado", monsters: ["Templario Inf", "Mago Inf", "Shaman Inf", "Ranger Inf"], zones: ["Pista +4"] },
    { item_name: "Excalibur Selado", monsters: ["Templario Inf", "Mago Inf", "Shaman Inf", "Ranger Inf"], zones: ["Pista +4"] },
    { item_name: "Kenten Selado", monsters: ["Templario Inf", "Mago Inf", "Shaman Inf", "Ranger Inf"], zones: ["Pista +4"] },
    { item_name: "Gae Bulg Selado", monsters: ["Templario Inf", "Mago Inf", "Shaman Inf", "Ranger Inf"], zones: ["Pista +4"] },
    { item_name: "Cetro Rithil Selado", monsters: ["Templario Inf", "Mago Inf", "Shaman Inf", "Ranger Inf"], zones: ["Pista +4"] },
    { item_name: "Dordje Selado", monsters: ["Templario Inf", "Mago Inf", "Shaman Inf", "Ranger Inf"], zones: ["Pista +4"] },
    { item_name: "Hrotti Selado", monsters: ["Templario Inf", "Mago Inf", "Shaman Inf", "Ranger Inf"], zones: ["Pista +4"] },
    { item_name: "Martelo Kaumodaki Selado", monsters: ["Templario Inf", "Mago Inf", "Shaman Inf", "Ranger Inf"], zones: ["Pista +4"] },
    { item_name: "Círculo Divino", monsters: ["Troll Insano"], zones: ["Erion"] }
];
